<?php

class CHANGES {
     const TYPE_COMMIT = 'commit';

     const FIELD_COMMIT_SHA1 = 'commit_sha1';
     const FIELD_COMMIT_ISSUE = 'commit_issue';
     const FIELD_COMMIT_AUTHOR = 'commit_author';
     const FIELD_COMMIT_MESSAGE = 'commit_message';

     const TYPE_ISSUE = 'issue';
     const VOCAB_ISSUE_COMPONENT = 'issue_component';
     const VOCAB_ISSUE_TAGS = 'issue_tags';
     const FIELD_ISSUE_NID = 'issue_nid';
     const FIELD_ISSUE_COMPONENT = 'issue_component';
     const FIELD_ISSUE_TAGS = 'issue_tags';
     const FIELD_ISSUE_RELATED = 'issue_related';
     const FIELD_ISSUE_CHANGE_RECORDS = 'issue_change_notices';

     const TYPE_CHANGE_NOTICE = 'changenotice';
     const FIELD_CHANGE_NID = 'change_nid';
}

/**
 * Convert CSS query to XPath query.
 *
 * @param  string $query CSS Query
 * @return string Xpath queyr
 */
function changes_css_to_xpath($query) {
  if (!class_exists('Symfony\Component\CssSelector\CssSelector')) {
    at_id(
      new Drupal\at_base\Autoloader(
        'Symfony\Component\CssSelector',
        at_library('sf2.css_selector')
      )
    )->register();
  }

  return Symfony\Component\CssSelector\CssSelector::toXPath($query);
}

/**
 * Implements hook_entity_template()
 */
function changes_entity_view_alter(&$build, $entity_type) {
    at_id(new Drupal\at_base\Hook\Entity\View_Alter($build, $entity_type))
      ->execute();
}

/**
 * Implements hook_url_outbound_alter()
 *
 * Change /taxonomy/term/%tag-id => /search?tag=%tag-name
 */
function changes_url_outbound_alter(&$path, &$options, $original_path) {
  if (empty($path)) {
        return;
    }

    if (0 !== strpos($original_path, 'taxonomy/term/')) {
        return;
    }

    if (!isset($options['entity'])) {
        $options['entity_type'] = 'taxonomy_term';

        // Get Term ID from path
        $tid = preg_replace('`taxonomy/term/(\d+)`', '$1', $original_path);

        $options['entity'] = taxonomy_term_load($tid);
    }

    if (!empty($options['entity'])) {
        switch ($options['entity']->vocabulary_machine_name) {
            case CHANGES::VOCAB_ISSUE_TAGS:
                $path = 'commits';
                $options['query']['tags'] = $options['entity']->name;
                break;

            case CHANGES::VOCAB_ISSUE_COMPONENT:
                $path = 'commits';
                $options['query']['component'] = $options['entity']->tid;
                break;
        }
    }
}
